version: "3.7"

services:
  axon-server:
    container_name: axon-server
    image: axoniq/axonserver
    ports:
      - 8024:8024
      - 8124:8124

  inventory-database:
    container_name: inventory-database
    image: mongo
    ports:
      - 27017:27017

  customer-database:
    container_name: customer-database
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432