server:
  port: 8090
spring:
  application:
    name: order-application
  data:
    mongodb:
      database: inventory
      host: localhost
      port: 27017
axon:
  axonserver:
    servers: localhost