server:
  port: 8090
spring:
  application:
    name: order-application
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
axon:
  axonserver:
    servers: localhost